import type { Metadata } from "next";
import {Inter,IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ThemeProvider } from "@/components/theme-provider";
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const ibmplexmono = IBM_Plex_Mono({
  weight: ["400", "700"],
  variable: "--font-plex-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${ibmplexmono.variable} antialiased`}
      >
        <TooltipProvider>
          <ThemeProvider
            attribute={"class"}
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >{children}</ThemeProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
